# Simple Test Workflow to verify GitHub Actions is working
name: Test Critical Words Setup

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
      checks: write
      statuses: write

    steps:
    - name: Test Environment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
        GITHUB_SHA: ${{ github.event.pull_request.head.sha }}
      run: |
        echo "🧪 Testing GitHub Actions Setup"
        echo "Repository: $GITHUB_REPOSITORY"
        echo "PR Number: $PR_NUMBER"
        echo "SHA: $GITHUB_SHA"
        echo "Token: $(if [ -n "$GITHUB_TOKEN" ]; then echo "✅ Present"; else echo "❌ Missing"; fi)"
        
        # Test Python
        python3 --version
        
        # Test basic GitHub API call
        if [ -n "$GITHUB_TOKEN" ] && [ -n "$GITHUB_REPOSITORY" ] && [ -n "$PR_NUMBER" ]; then
          echo "🔍 Testing GitHub API access..."
          curl -H "Authorization: token $GITHUB_TOKEN" \
               -H "Accept: application/vnd.github.v3+json" \
               "https://api.github.com/repos/$GITHUB_REPOSITORY/pulls/$PR_NUMBER" \
               | head -20
        else
          echo "❌ Cannot test API - missing environment variables"
        fi
        
        echo "✅ Test completed!"

    - name: Post Test Comment
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_REPOSITORY: ${{ github.repository }}
        PR_NUMBER: ${{ github.event.pull_request.number }}
      run: |
        if [ -n "$GITHUB_TOKEN" ] && [ -n "$GITHUB_REPOSITORY" ] && [ -n "$PR_NUMBER" ]; then
          curl -X POST \
            -H "Authorization: token $GITHUB_TOKEN" \
            -H "Accept: application/vnd.github.v3+json" \
            "https://api.github.com/repos/$GITHUB_REPOSITORY/issues/$PR_NUMBER/comments" \
            -d '{"body":"🧪 **Test Workflow Running Successfully!**\n\nThe GitHub Actions setup is working correctly. The Critical Words Guard should also work now.\n\n*You can delete this comment and remove the test workflow file.*"}'
          
          echo "✅ Posted test comment to PR"
        else
          echo "❌ Cannot post comment - missing environment variables"
        fi